apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: dockersample-xyz-tls
spec:
    secretName: dockersample-xyz
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: dockersample.xyz
    dnsNames:
        - dockersample.xyz
        - www.dockersample.xyz
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - dockersample.xyz
                - www.dockersample.xyz